version: "2"            # must be a string in v2
run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - gosimple
    - misspell
    - errcheck
issues: {}              # v2: remove exclude-use-default; keep minimal for now
