version: "2"   # v2 requires a string

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - errcheck

formatters:
  enable:
    - gofmt
    - goimports

# v2 removed 'exclude-use-default'. If you need exclusions later,
# use 'linters.exclusions' / 'formatters.exclusions'.
issues: {}
