- version: 2
+ version: "2"   # v2 schema requires a string

- issues:
-   exclude-use-default: false
+# v2 removed 'exclude-use-default'. If you need exclusions later,
+# use 'linters.exclusions' / 'formatters.exclusions'. Keep minimal for now.
+issues: {}
