version: 2

run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - errcheck
formatters:
  enable:
    - gofmt
    - goimports
issues:
  exclude-use-default: false
