project_name: glyph

before:
  hooks:
    - go test ./...

builds:
  - id: glyphctl
    main: ./cmd/glyphctl
    binary: glyphctl
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: glyphd
    main: ./cmd/glyphd
    binary: glyphd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: quickstartseed
    main: ./cmd/quickstartseed
    binary: quickstartseed
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: glyphctl-archive
    builds:
      - glyphctl
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip
  - id: glyphd-archive
    builds:
      - glyphd
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
  - id: quickstartseed-archive
    builds:
      - quickstartseed
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "glyph_{{ .Tag }}_checksums.txt"

nfpms:
  - id: glyphctl-linux-packages
    package_name: glyphctl
    builds:
      - glyphctl
    formats:
      - deb
      - rpm
    maintainer: Rowan Dark <security@rowandark.dev>
    description: Glyph automation toolkit command-line interface.
    homepage: https://github.com/RowanDark/Glyph
    license: Apache-2.0
    bindir: /usr/local/bin
    priority: optional
    section: utils
    file_name_template: "{{ .PackageName }}_{{ .Tag }}_{{ .Arch }}"

dockers:
  - id: glyphctl-image
    use: buildx
    image_templates:
      - ghcr.io/rowandark/glyphctl:{{ .Version }}
      - ghcr.io/rowandark/glyphctl:latest
    dockerfile: Dockerfile
    build_flag_templates:
      - "--build-arg=VERSION={{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64

release:
  github:
    owner: RowanDark
    name: Glyph

changelog:
  use: git
