version: 2

project_name: 0xgen

before:
  hooks:
    # Run go mod tidy to ensure go.sum is up to date
    - go mod tidy
    # Verify the build compiles (tests run separately in CI)
    - go build ./...

builds:
  - id: 0xgenctl
    main: ./cmd/0xgenctl
    binary: 0xgenctl
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: 0xgend
    main: ./cmd/0xgend
    binary: 0xgend
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: quickstartseed
    main: ./cmd/quickstartseed
    binary: quickstartseed
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: 0xgenctl-archive
    builds:
      - 0xgenctl
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip
  - id: 0xgend-archive
    builds:
      - 0xgend
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
  - id: quickstartseed-archive
    builds:
      - quickstartseed
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "0xgen_{{ .Tag }}_checksums.txt"

nfpms:
  - id: 0xgenctl-linux-packages
    package_name: 0xgenctl
    builds:
      - 0xgenctl
    formats:
      - deb
      - rpm
    maintainer: Rowan Dark <security@rowandark.dev>
    description: 0xgen automation toolkit command-line interface.
    homepage: https://github.com/RowanDark/0xgen
    license: Apache-2.0
    bindir: /usr/local/0xgen/bin
    priority: optional
    section: utils
    vendor: 0xgen Project
    provides:
      - 0xgenctl
    dependencies:
      - ca-certificates
    contents:
      - src: LICENSE
        dst: /usr/share/doc/0xgenctl/LICENSE
      - src: README.md
        dst: /usr/share/doc/0xgenctl/README.md
    file_name_template: "{{ .PackageName }}_{{ .Tag }}_{{ .Arch }}"
    scripts:
      postinstall: packaging/linux/postinstall.sh

dockers:
  - id: 0xgenctl-image
    use: buildx
    push: true
    image_templates:
      - ghcr.io/rowandark/0xgenctl:{{ .Version }}
      - ghcr.io/rowandark/0xgenctl:latest
    dockerfile: Dockerfile
    build_flag_templates:
      - "--build-arg=VERSION={{ .Version }}"
      - "--platform=linux/amd64,linux/arm64"

release:
  github:
    owner: RowanDark
    name: 0xgen

changelog:
  use: git
