# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oxg/plugin_bus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oxg/plugin_bus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as oxg_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14oxg/plugin_bus.proto\x12\x0eoxg.plugin_bus\x1a\x10oxg/common.proto\"l\n\x0bPluginEvent\x12,\n\x05hello\x18\x01 \x01(\x0b\x32\x1b.oxg.plugin_bus.PluginHelloH\x00\x12&\n\x07\x66inding\x18\x02 \x01(\x0b\x32\x13.oxg.common.FindingH\x00\x42\x07\n\x05\x65vent\"\x8a\x01\n\x0bPluginHello\x12\x12\n\nauth_token\x18\x01 \x01(\t\x12\x13\n\x0bplugin_name\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\x15\n\rsubscriptions\x18\x04 \x03(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x05 \x03(\t\x12\x18\n\x10\x63\x61pability_token\x18\x06 \x01(\t\"X\n\x17PluginCapabilityRequest\x12\x12\n\nauth_token\x18\x01 \x01(\t\x12\x13\n\x0bplugin_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x03 \x03(\t\"J\n\x15PluginCapabilityGrant\x12\x18\n\x10\x63\x61pability_token\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpires_at_unix\x18\x02 \x01(\x03\"W\n\tHostEvent\x12\x14\n\x0c\x63ore_version\x18\x01 \x01(\t\x12+\n\nflow_event\x18\x02 \x01(\x0b\x32\x15.oxg.common.FlowEventH\x00\x42\x07\n\x05\x65vent2\xbb\x01\n\tPluginBus\x12I\n\x0b\x45ventStream\x12\x1b.oxg.plugin_bus.PluginEvent\x1a\x19.oxg.plugin_bus.HostEvent(\x01\x30\x01\x12\x63\n\x11GrantCapabilities\x12\'.oxg.plugin_bus.PluginCapabilityRequest\x1a%.oxg.plugin_bus.PluginCapabilityGrantB*Z(github.com/RowanDark/0xgen/proto/oxg;oxgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oxg.plugin_bus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/RowanDark/0xgen/proto/oxg;oxg'
  _globals['_PLUGINEVENT']._serialized_start=58
  _globals['_PLUGINEVENT']._serialized_end=166
  _globals['_PLUGINHELLO']._serialized_start=169
  _globals['_PLUGINHELLO']._serialized_end=307
  _globals['_PLUGINCAPABILITYREQUEST']._serialized_start=309
  _globals['_PLUGINCAPABILITYREQUEST']._serialized_end=397
  _globals['_PLUGINCAPABILITYGRANT']._serialized_start=399
  _globals['_PLUGINCAPABILITYGRANT']._serialized_end=473
  _globals['_HOSTEVENT']._serialized_start=475
  _globals['_HOSTEVENT']._serialized_end=562
  _globals['_PLUGINBUS']._serialized_start=565
  _globals['_PLUGINBUS']._serialized_end=752
# @@protoc_insertion_point(module_scope)
