# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oxg/secrets.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oxg/secrets.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11oxg/secrets.proto\x12\x0boxg.secrets\"`\n\x13SecretAccessRequest\x12\x13\n\x0bplugin_name\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x13\n\x0bsecret_name\x18\x03 \x01(\t\x12\x10\n\x08scope_id\x18\x04 \x01(\t\"%\n\x14SecretAccessResponse\x12\r\n\x05value\x18\x01 \x01(\t2a\n\rSecretsBroker\x12P\n\tGetSecret\x12 .oxg.secrets.SecretAccessRequest\x1a!.oxg.secrets.SecretAccessResponseB*Z(github.com/RowanDark/0xgen/proto/oxg;oxgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oxg.secrets_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/RowanDark/0xgen/proto/oxg;oxg'
  _globals['_SECRETACCESSREQUEST']._serialized_start=34
  _globals['_SECRETACCESSREQUEST']._serialized_end=130
  _globals['_SECRETACCESSRESPONSE']._serialized_start=132
  _globals['_SECRETACCESSRESPONSE']._serialized_end=169
  _globals['_SECRETSBROKER']._serialized_start=171
  _globals['_SECRETSBROKER']._serialized_end=268
# @@protoc_insertion_point(module_scope)
