# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glyph/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glyph/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12glyph/common.proto\x12\x0cglyph.common\"\xba\x01\n\x07\x46inding\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12(\n\x08severity\x18\x03 \x01(\x0e\x32\x16.glyph.common.Severity\x12\x35\n\x08metadata\x18\x04 \x03(\x0b\x32#.glyph.common.Finding.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8e\x01\n\tFlowEvent\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.glyph.common.FlowEvent.Type\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"G\n\x04Type\x12\x1a\n\x16\x46LOW_EVENT_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x46LOW_REQUEST\x10\x01\x12\x11\n\rFLOW_RESPONSE\x10\x02*[\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x07\n\x03LOW\x10\x02\x12\n\n\x06MEDIUM\x10\x03\x12\x08\n\x04HIGH\x10\x04\x12\x0c\n\x08\x43RITICAL\x10\x05\x42.Z,github.com/RowanDark/Glyph/proto/glyph;glyphb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glyph.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/RowanDark/Glyph/proto/glyph;glyph'
  _globals['_FINDING_METADATAENTRY']._loaded_options = None
  _globals['_FINDING_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEVERITY']._serialized_start=370
  _globals['_SEVERITY']._serialized_end=461
  _globals['_FINDING']._serialized_start=37
  _globals['_FINDING']._serialized_end=223
  _globals['_FINDING_METADATAENTRY']._serialized_start=176
  _globals['_FINDING_METADATAENTRY']._serialized_end=223
  _globals['_FLOWEVENT']._serialized_start=226
  _globals['_FLOWEVENT']._serialized_end=368
  _globals['_FLOWEVENT_TYPE']._serialized_start=297
  _globals['_FLOWEVENT_TYPE']._serialized_end=368
# @@protoc_insertion_point(module_scope)
