# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glyph/plugin_bus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glyph/plugin_bus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as glyph_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16glyph/plugin_bus.proto\x12\x10glyph.plugin_bus\x1a\x12glyph/common.proto\"p\n\x0bPluginEvent\x12.\n\x05hello\x18\x01 \x01(\x0b\x32\x1d.glyph.plugin_bus.PluginHelloH\x00\x12(\n\x07\x66inding\x18\x02 \x01(\x0b\x32\x15.glyph.common.FindingH\x00\x42\x07\n\x05\x65vent\"Z\n\x0bPluginHello\x12\x12\n\nauth_token\x18\x01 \x01(\t\x12\x13\n\x0bplugin_name\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\x15\n\rsubscriptions\x18\x04 \x03(\t\"Y\n\tHostEvent\x12\x14\n\x0c\x63ore_version\x18\x01 \x01(\t\x12-\n\nflow_event\x18\x02 \x01(\x0b\x32\x17.glyph.common.FlowEventH\x00\x42\x07\n\x05\x65vent2Z\n\tPluginBus\x12M\n\x0b\x45ventStream\x12\x1d.glyph.plugin_bus.PluginEvent\x1a\x1b.glyph.plugin_bus.HostEvent(\x01\x30\x01\x42,Z*github.com/example/glyph/proto/glyph;glyphb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glyph.plugin_bus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/example/glyph/proto/glyph;glyph'
  _globals['_PLUGINEVENT']._serialized_start=64
  _globals['_PLUGINEVENT']._serialized_end=176
  _globals['_PLUGINHELLO']._serialized_start=178
  _globals['_PLUGINHELLO']._serialized_end=268
  _globals['_HOSTEVENT']._serialized_start=270
  _globals['_HOSTEVENT']._serialized_end=359
  _globals['_PLUGINBUS']._serialized_start=361
  _globals['_PLUGINBUS']._serialized_end=451
# @@protoc_insertion_point(module_scope)
