/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as RunDetailRouteImport } from './routes/runs.$runId'
import { Route as RunsComposerRouteImport } from './routes/runs.composer'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'

const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const RunDetailRoute = RunDetailRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsComposerRoute = RunsComposerRouteImport.update({
  id: '/runs/composer',
  path: '/runs/composer',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/flows': typeof FlowsRoute
  '/runs': typeof RunsRoute
  '/runs/$runId': typeof RunDetailRoute
  '/runs/composer': typeof RunsComposerRoute
  '/scope': typeof ScopeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/flows': typeof FlowsRoute
  '/runs': typeof RunsRoute
  '/runs/$runId': typeof RunDetailRoute
  '/runs/composer': typeof RunsComposerRoute
  '/scope': typeof ScopeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/flows': typeof FlowsRoute
  '/runs': typeof RunsRoute
  '/runs/$runId': typeof RunDetailRoute
  '/runs/composer': typeof RunsComposerRoute
  '/scope': typeof ScopeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cases' | '/flows' | '/runs' | '/runs/$runId' | '/runs/composer' | '/scope'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cases' | '/flows' | '/runs' | '/runs/$runId' | '/runs/composer' | '/scope'
  id: '__root__' | '/' | '/cases' | '/flows' | '/runs' | '/runs/$runId' | '/runs/composer' | '/scope'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  FlowsRoute: typeof FlowsRoute
  RunsRoute: typeof RunsRoute
  RunDetailRoute: typeof RunDetailRoute
  RunsComposerRoute: typeof RunsComposerRoute
  ScopeRoute: typeof ScopeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/composer': {
      id: '/runs/composer'
      path: '/runs/composer'
      fullPath: '/runs/composer'
      preLoaderRoute: typeof RunsComposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  FlowsRoute: FlowsRoute,
  RunsRoute: RunsRoute,
  RunDetailRoute: RunDetailRoute,
  RunsComposerRoute: RunsComposerRoute,
  ScopeRoute: ScopeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
