on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (vX.Y.Z)"
        required: true

jobs:
  bump:
    if: ${{ github.repository_owner == 'RowanDark' && (github.event_name == 'workflow_dispatch' || github.event.release.tag_name != '') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine tag
        id: release_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          elif [[ -n "${{ github.event.inputs.tag }}" ]]; then
            echo "tag=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF_NAME}" =~ ^v ]]; then
            echo "tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          else
            echo "No release tag available" >&2
            exit 1
          fi
      - name: Update tap (guarded)
        if: ${{ secrets.HOMEBREW_TAP_TOKEN != '' }}
        run: ./scripts/update-brew-formula.sh "${{ steps.release_tag.outputs.tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
      - name: Note skipped tap bump
        if: ${{ secrets.HOMEBREW_TAP_TOKEN == '' }}
        run: echo "Tap bump skipped: HOMEBREW_TAP_TOKEN missing."
