on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bump:
    if: ${{ github.repository_owner == 'RowanDark' && (github.event_name == 'workflow_dispatch' || github.event.release.tag_name != '') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update tap (guarded)
        if: ${{ secrets.HOMEBREW_TAP_TOKEN != '' }}
        run: ./scripts/update-brew-formula.sh "${{ github.event.release.tag_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
      - name: Note skipped tap bump
        if: ${{ secrets.HOMEBREW_TAP_TOKEN == '' }}
        run: echo "Tap bump skipped: HOMEBREW_TAP_TOKEN missing."
