name: 0xgen homebrew-smoke

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  brew:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew
        run: brew update
      - name: Install 0xgenctl from tap
        run: |
          set -euxo pipefail
          brew tap rowandark/glyph
          brew install glyph
          0xgenctl --version
